# Generated by Django 3.1 on 2020-08-31 05:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200824_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='listCafes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('list_cafe_name', models.CharField(max_length=200)),
                ('list_cafe_address', models.CharField(max_length=200)),
                ('list_cafe_long', models.FloatField()),
                ('list_cafe_lat', models.FloatField()),
                ('list_geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'a_cafes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mapCafes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(max_length=200)),
                ('cafe_address', models.CharField(max_length=200)),
                ('cafe_long', models.FloatField()),
                ('cafe_lat', models.FloatField()),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'a_cafes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ACafes',
        ),
    ]
