# Generated by Django 3.1 on 2020-08-31 05:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200831_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='listSectionCafes',
            fields=[
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('list_cafe_name', models.CharField(max_length=200)),
                ('list_cafe_address', models.CharField(max_length=200)),
                ('list_cafe_long', models.FloatField()),
                ('list_cafe_lat', models.FloatField()),
                ('list_geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'a_cafes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mapSectionCafes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(max_length=200)),
                ('cafe_address', models.CharField(max_length=200)),
                ('cafe_long', models.FloatField()),
                ('cafe_lat', models.FloatField()),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'a_cafes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='listCafes',
        ),
        migrations.DeleteModel(
            name='mapCafes',
        ),
    ]
