# Generated by Django 3.1.7 on 2021-08-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0005_sharedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='cafe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='testingland.mapcafes'),
        ),
    ]
