# Generated by Django 3.1.7 on 2021-08-10 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0006_auto_20210810_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedListLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('list', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='testingland.userlist')),
            ],
        ),
    ]
