# Generated by Django 3.1.7 on 2021-09-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0007_sharedlistlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlistlink',
            name='list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testingland.userlist'),
        ),
    ]
