# Generated by Django 3.1.7 on 2021-09-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingland', '0008_auto_20210922_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
