# Generated by Django 3.1.7 on 2021-07-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcafes',
            name='image_embed',
        ),
        migrations.AlterField(
            model_name='mapcafes',
            name='description',
            field=models.CharField(max_length=15000),
        ),
    ]
