# Generated by Django 3.1 on 2020-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='venues',
            name='venue_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venues',
            name='venue_long',
            field=models.FloatField(null=True),
        ),
    ]
