# Generated by Django 3.1.7 on 2021-07-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0002_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='liked_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testingland.mapcafes'),
        ),
    ]
