# Generated by Django 3.1.7 on 2021-07-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0002_auto_20210708_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservenue',
            unique_together=set(),
        ),
    ]
