# Generated by Django 3.1 on 2020-09-27 08:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingland', '0003_testlist_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestList',
            new_name='WishList',
        ),
    ]
