# Generated by Django 3.1.7 on 2021-08-10 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0004_auto_20210708_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testingland.mapcafes', unique=True)),
            ],
        ),
    ]
