# Generated by Django 3.1 on 2020-09-28 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingland', '0004_auto_20200927_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venues', models.ManyToManyField(to='testingland.Venues')),
            ],
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
