# Generated by Django 3.1 on 2020-09-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0005_auto_20200928_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuelist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='venuelist',
            name='venues',
        ),
    ]
