# Generated by Django 3.1 on 2020-09-30 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0006_auto_20200930_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuelist',
            name='venue_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
