# Generated by Django 3.1 on 2020-09-30 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0007_venuelist_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='venue_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
