# Generated by Django 3.1 on 2021-03-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0011_auto_20210331_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='user_id',
            new_name='user',
        ),
    ]
