# Generated by Django 3.1.7 on 2021-04-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0013_userfollowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconnections',
            old_name='following_user',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='user',
            new_name='follower',
        ),
    ]
