# Generated by Django 3.1.7 on 2021-04-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0015_auto_20210412_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotionCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=255)),
                ('promo_description', models.CharField(max_length=1000)),
                ('promo_quantity', models.IntegerField()),
                ('promo_venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testingland.mapcafes')),
            ],
        ),
    ]
