# Generated by Django 3.1.7 on 2021-04-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingland', '0016_promotioncampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncampaign',
            name='promo_description',
        ),
    ]
