# Generated by Django 3.1.7 on 2021-04-18 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingland', '0017_remove_promotioncampaign_promo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservenue',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingland.userlist'),
        ),
        migrations.CreateModel(
            name='venueComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testingland.mapcafes')),
            ],
        ),
        migrations.CreateModel(
            name='replyComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_comment', models.CharField(max_length=10000)),
                ('original_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testingland.venuecomments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
